# Generated by Django 5.0.14 on 2026-04-06 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('companies', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='approvalflow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='companies.company'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalflow'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalstep'),
        ),
        migrations.AddIndex(
            model_name='approvalflow',
            index=models.Index(fields=['company', 'is_active'], name='approvals_a_company_8c5f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['flow', 'order'], name='approvals_a_flow_id_9bf009_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['expense', 'actor'], name='approvals_a_expense_4e5a63_idx'),
        ),
    ]
