# Generated by Django 5.0.14 on 2026-04-06 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['company', 'status'], name='cards_card_company_70d6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['user'], name='cards_card_user_id_318eab_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', 'transaction_at'], name='cards_cardt_card_id_0adda6_idx'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['external_id'], name='cards_cardt_externa_e07b29_idx'),
        ),
    ]
