# Generated by Django 5.0.14 on 2026-04-06 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals & Entertainment'), ('fuel', 'Fuel'), ('accommodation', 'Accommodation'), ('medical', 'Medical'), ('telecom', 'Telecom'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('merchant_mcc', models.CharField(blank=True, max_length=10)),
                ('expense_date', models.DateField()),
                ('receipt_key', models.CharField(blank=True, max_length=500)),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reimbursed', 'Reimbursed')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_policy_flagged', models.BooleanField(default=False)),
                ('policy_flag_reason', models.TextField(blank=True)),
                ('current_step', models.PositiveSmallIntegerField(default=0)),
                ('total_steps', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_type', models.CharField(choices=[('amount_limit', 'Per-transaction amount limit'), ('receipt_required', 'Receipt required above amount'), ('category_block', 'Category blocked for role'), ('duplicate_check', 'Duplicate detection window'), ('weekend_block', 'Block weekend submissions'), ('auto_approve', 'Auto-approve rule')], max_length=30)),
                ('applies_to_role', models.CharField(blank=True, max_length=20)),
                ('applies_to_category', models.CharField(blank=True, max_length=30)),
                ('value', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
