# Generated by Django 5.0.14 on 2026-04-06 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_initial'),
        ('companies', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_policies', to='companies.company'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'status'], name='expenses_ex_company_56b42f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'user'], name='expenses_ex_company_224535_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_date'], name='expenses_ex_company_78e6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['card'], name='expenses_ex_card_id_e2af57_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepolicy',
            index=models.Index(fields=['company', 'is_active'], name='expenses_ex_company_90abff_idx'),
        ),
    ]
